#
# Generic settings for SocialCore
#
plugin-prefix: '&8[&bSocial&8]'
enable-courts: true
enable-marriages: true
enable-genders: true
#
# SQL settings for database storage
#
sql:
 host: localhost
 dbname: minecraft
 user: changeme
 pass: changeme