#Marriage Rings:
marriage-rings:
    1: '331 &9Ruby Marriage Gem'
    2: '388 &9Emerald Marriage Gem'
    3: '264 &5Diamond Marriage Gem'
    4: '385 &5Heart of Summer'
    5: '399 &6Star Marriage Gem'
    6: '399 &5Star Marriage Gem'
    7: '399:1 &5Star Marriage Gem'
    8: '399 &6Heirloom Marriage Gem'
    9: '322 &6Crystaline Fall Marriage Apple'
    10: '322 &5Crystaline Fall Marriage Apple'
    11: '322:1 &6Crystaline Fall Marriage Apple'
    12: '264 &5Ten Carat Diamond Ring'
    13: '370:1 &5Tear of Nerfs'
    14: '370 &5Tear of Nerfs'
    15: '263:2 &5The Frigid Heart'
    16: '388:0 &5Gem of New Life'
    17: '91:0 &5Ghastly Garnet'
    18: '86:0 &5Ghastly Garnet'
    18: '264:0 &5Morbid Moonstone'
#The required distance (in blocks) between the priest and both couples:
priest-marriage-distance: 10
#The required distance (in blocks) between each partner:
marriage-couple-distance: 5
#
piggyback-cooldown: 90s
marriage-food-share-distance: 0
marriage-inventory-share-distance: 0
kiss-heal-amount: 0
login-petname-message: "&d**Your {pet-name}&d has signed in**"
logout-petname-message: "&d**Your {pet-name}&d has signed out**"
petname-change-spouse-message: "&dYour {spouse-petname}&d has given you the name pet name: {new-petname}"
#
#The required distance for married couples to get bonus xp from each other
marriage-xp-bonus-distance: 5
#The percent of the killer's xp to give to their significant other (0.0 - 1.0)
marriage-xp-bonus-percent: 0.5
#Should the kissing effect be played
kissing-heart-effect: true
#how many days it takes to re-marry a player.
divorce-propose-cooldown: 5d
#
courts:
  policy:
    lang:
     state-descriptions:
       UNCONFIRMED: "This has not yet been confirmed by all the judges"
       MAIN_VOTING: "This policy is currently under vote by all players."
       IN_EFFECT: "This policy is in effect"
       FAILED: "This policy failed to become in effect"
     policy-draft-already-pending: "&6[&eCourt&6]&c There is already a policy awaiting approval."
     policy-new: "&6[&eCourt&6]&c You have received a book for which you should write your intended policy. You have a 300 character limit, and should include wether are not a punishment is applicable to ths policy."
     policy-finish-characters: "&6[&eCourt&6]&c This policy exceeds the max character count. Try simplifying the policy or splitting into into multiple policies."
     policy-finish: "&6[&eCourt&6]&c You have published your policy for review. Three other judges will be required to approve the policy before it is made public."
     policy-official-votes: "&6[&eCourt&6]&c The policy {policy-number} has been approved by the community, and is now official."
     policy-official-auto: "&6[&eCourt&6]&c The policy {policy-number} has been approved by default."
    judges-required-to-confirm: 3
    policy-approval-rate-removed: 40
    policy-approval-rate-required: 60
    character-max: 300
    policy-required-votes: 100
    #Instructions are added to end automatically.
    unpassed-policy-icon-base-item: "book 1 name:&aPolicy_{policy-number} lore:&3{policy-text}|{vote-status}|&aApproval_Rating:_{approval-rating}|&eVote_Progress:_{vote-progress}|{policy-status-description}"
    passed-policy-icon-base-item: "book 1 name:&aPolicy_{policy-number} lore:&3{policy-text}|{vote-status}|{policy-status-description}"
    policy-check-interval: 4m # How often to force check of  if should autopass, etc.
    policy-autopass-time: 3d # How long to wait before auto approving in main voting.
    policy-confirm-timeout: 1d # How long before failing if didn't get the confirmations.
  silence-mute-length: 10s
  silence-court-effects:
    title:
      title: "&cOrder!"
      subtitle: "&7Quiet in the court"
      fade-in: 1s
      stay: 10s
      fade-out: 5s
    sounds:
      BLOCK_ANVIL_USE:
        volume: 3
        pitch: 0.4
  court-session-teleport-effects:
    title:
      title: "&aJudge {judge-name} teleported to {location}"
      subtitle: "~~"
      fade-in: 1s
      stay: 40t
      fade-out: 10t
  elections:
    wait-time: 7d
  court-session-start-effects:
    title:
      title: "&eSilence in the courtroom"
      subtitle: "&7Honerable Judge &e{judge-name}&7 presiding"
      fade-in: 1s
      stay: 10s
      fade-out: 5s
    sounds:
      BLOCK_ANVIL_USE:
        volume: 3
        pitch: 0.4
  court-session-end-effects:
    title:
      title: "&eCourt is adjourned"
      subtitle: "&7Thank you for your participation"
      fade-in: 1s
      stay: 10s
      fade-out: 5s
    sounds:
      BLOCK_ANVIL_USE:
        volume: 3
        pitch: 0.4
  judge-permissions:
    - "towny.chat.justice"
    - "sc.title.judge"
    - "magicspells.cast.judgeinspect"
    - "magicspells.cast.royal-gavel"
    - "lwc.shownotices"
  secretary-permissions:
    - "towny.chat.justice"
  case-filing-cost: 100
  category-config: 
    abandoned:
      permit-item: "paper 1 Unbreaking:1 name:&9Building_Permit lore:&6Awarded_to:_{citizen_name}|&5by_Judge:_{judge-name}|&2Permission_to_build/destroy|&2at_{location}|&7Permit|&3Bind_On_Pickup"
    abandoned-chest:
      permit-item: "paper 1 Unbreaking:1 name:&Chest_Permit lore:&6Awarded_to:_{citzen-name}|&5by_Judge:_{judge-name}|&2Permission_to_loot_chest(s)|&2at_{location}|&7Permit|&3Bind_On_Pickup"
  court-rooms: 
    test-courtroom: 
      effects-location: "new_vb,-1458,103,433"
      judge-chair-location: "new_vb,-1460,103,433"
      region: court
      tp-location: "new_vb,-1394,105,433"
  fine-payment-interval: 5m
  fine-payment-percentage: 15
  judge-approval-rate-demoted: 40
  judge-approval-rate-required: 60
  judge-inactive-days-allowed: 15
  judge-required-votes: 300
  lang:
    command-not-in-session: "This command can only be used while court is in session"
    judge-prefix: "<J>"
    court-session-plaintiff-prefix: "<Plaintiff>"
    court-session-defendant-prefix: "<Defendant>"
    judge-prefix: "&6<&eJ&6>"
    court-session-plaintiff-prefix: "&6<Plaintiff>"
    court-session-defendant-prefix: "&6<Defendant>"
    policy-draft-already-pending: "&6[&eCourt&6]&c There is already a policy awaiting approval."
    policy-new: "&6[&eCourt&6]&c You have received a book for which you should write your intended policy. You have a 300 character limit, and should include wether are not a punishment is applicable to ths policy."
    policy-finish-characters: "&6[&eCourt&6]&c This policy exceeds the max character count. Try simplifying the policy or splitting into into multiple policies."
    policy-finish: "&6[&eCourt&6]&c You have published your policy for review. Three other judges will be required to approve the policy before it is made public."
    policy-start-voting: "A new policy has been moved to voting. Please cast your votes at /policies"
    policy-official-votes: "&6[&eCourt&6]&c The policy {policy-number} has been approved by the community, and is now official."
    policy-official-auto: "&6[&eCourt&6]&c The policy {policy-number} has been failed by default."
    vote-status:
      unconfirmed: You have not confirmed this policy.
      confirmed: You have confirmed this policy.
      approved: You have approved of this policy.
      disapproved: You have disapproved of this policy.
      abstained: You have not yet voted on this policy.
    case-category-descriptions:
      ABANDONED: "Cases concerning abandoned houses or towns"
      DIVORCE: "Divorce is when a married couple wishes to end their union."
      OTHER: "Cases which do not fit in any other category"
      TRESPASSING: "Trespassing involves a player repeatedly entering a player's property even after being asked to leave."
      CIVIL_MARRIAGE: "When two players wish to be married by a judge, discreetly."
      SEX_CHANGE: "When a player needs to change their picked sex."
    citizen-stall: 
      case-already-filed: "&6[&eCourt&6]&c Case has already been filed"
      case-book-empty: "&6[&eCourt&6]&c This case book is empty. You need to fill it with the details of your case."
      confirm: "&6[&eCourt&6]&a This is where you get court case documents. Clicking this stall again will charge you &e{cost}&a voxels and give you court documents, which you can file to have your case reviewed."
      gave-court-documents: "&6[&eCourt&6]&a You have been given a book to fill in about your case, right click the stall to submit it."
      on-cooldown: "&6[&eCourt&6]&c Please wait a moment before using this stall again."
      submitted: "&6[&eCourt&6]&a Your case has been submitted for processing. You will be updated as soon as the status of your case changes."
    confirm-nominate-self: "&6[&eCourt&6]&a Typing &6/election run&a again will nominate you in this election and charge you&e {cost}&a voxels."
    judge-inactive-all: "&6[&eCourt&6]&a {judge}&c was innactive for over a week, and was removed from office."
    judge-inactive-judge: "&6[&eCourt&6]&c You were innactive for too many days, and were removed from office."
    election-no-slots: "&6[&eCourt&6]&c There are no available judge slots. Elections are only enabled when there are open judge slots. For more information, type &6/help court"
    secretary: 
      not-secretary-message: "{player-name} is not one of your secretaries"
      removed-message: "You have removed {player-name} as your secretary"
      requested-accept-message: "&aYou have accepted {judge-name}'s request that you become their secretary"
      requested-confirm-message: "&aJudge {judge-name} has requested that you become their secretary. /secretary accept to accept or /secretary deny to deny this request"
      requested-deny-message: "You have denied {judge-name}'s request that you become their secretary"
      requester-accepted-message: "{requested-name} is now your secetary"
      requester-denied-message: "{requested-name} has denied your secetary request"
      requesting-message: "&6[&eCourt&6]&a A request has been sent to {requested-name} to become your secretary."
  max-judges: 4
  nominate-cost: 10000
  notifier: 
    messages: 
      judge-elected-all:
        base-message: "&6[&eCourt&6]&e {judge-name}&a has been successfully elected as a judge. Congratulations!"
      case-assigned-time:
        base-message: "&6[&eCourt&6]&e {judge-name}&a has scheduled &6{case-name}&a to &6{case-datetime}&a."
      judge-inactive-all: 
        base-message: "&6[&eCourt&6]&e Judge {judge-name}&c was inactive for too many days and was removed from office."
      judge-inactive-judge: 
        base-message: "&6[&eCourt&6]&c You were inactive for too many days and have been removed from office"
        timeout: 3d
      judge-nominated-all: 
        base-message: "&6[&eCourt&6]&e {player-name}&a has been nominated to become a judge. Type &6/election&a to review the candidates."
      judge-nominated-self: 
        base-message: "&6[&eCourt&6]&e {player-name}&a, you have been nominated to become a judge. Please review &6/help election&a and &6/help judge&a."
        timeout: 14d
      judge-removed-rating-all: 
        base-message: "&6[&eCourt&6]&c Judge &a{judge-name}&c has been removed from office with an approval rating of &c{approval-rating}."
      judge-removed-rating-judge: 
        base-message: "&6[&eCourt&6]&c You have been removed from office with an approval rating of {approval-rating}."
        timeout: 7d
      judge-upcoming-case: 
        base-message: "&6[&eCourt&6]&e Judge {name}, you have {case-name} at {case-datetime}"
        upcoming-time: 7d
      ongoing-case-all: 
        base-message: "&6[&eCourt&6]&e Judge {judge-name} is presiding over case: &6{case-number} {case-name} &e(&6{case-category}&e)&e, with plaintiff: &a{case-plaintiff}&e. Type &6/warp court&e to participate and receive rewards."
        enabled: true
      ongoing-case-participant: 
        base-message: "&6[&eCourt&6]&e You are involved in an ongoing court session, please teleport with &6/court tp"
      court-session-end:
        base-message: "&6[&eCourt&6]&e {case-name} is now adjourned by {judge-name}"
      participant-upcoming-case: 
        base-message: "&6[&eCourt&6]&e You are involved in {case-name} at {case-datetime}"
        upcoming-time: 7d
      secretary-removed: 
        base-message: "&6[&eCourt&6]&a {judge-name}&c has removed you as one of their secretaries."
        timeout: 7d
      vote-notification: 
        approval: "&6[&eCourt&6]&a Somebody approved of you, your approval rate is now {approval-rating} with {approvals} approvals and {disapprovals} disapprovals."
        disapproval: "&6[&eCourt&6]&a Somebody disapproved of you, your approval rate is now {approval-rating} with {approvals} approvals and {disapprovals} disapprovals."
      vote-summary: 
        approval: "&6[&eCourt&6]&a {new-approvals} citizens have recently approved of you. Approval rating: {approval-rating}"
        both: "&6[&eCourt&6]&a {new-approvals} citizens have recently approved of you and {new-disapprovals} citizens have disapproved of you "
        disapproval: "&6[&eCourt&6]&a {new-disapprovals} citizens have recently disapproved of you. Approval rating: {approval-rating}"
        timeout: 1d
  rewards: 
    session:
      - 'gold_nugget 1 Unbreaking:1 name:&9Justice_Token lore:&9&o"Fiat_justitia,|&9&oet_pereat_mundus."|&6Royal_currency_used|&6in_the_municipal_system.'
    court-vote: 
      - 'gold_ingot 1'
    judgement: 
      - 'gold_nugget 1 Unbreaking:1 name:&5Arbiter_Token lore:&9&o"Fiat_justitia,|&9&oet_pereat_mundus."|&6Royal_currency_used|&6in_the_municipal_system.'
    process: 
      - 'gold_nugget 1 Unbreaking:1 name:&9Justice_Token lore:&9&o"Fiat_justitia,|&9&oet_pereat_mundus."|&6Royal_currency_used|&6in_the_municipal_system.'
  secretaries-per-judge: 2
  time-between-vote-messages: 10m
sql:
 host: localhost
 dbname: minecraft
 user: changeme
 pass: changeme