#Marriage Rings:
marriage-rings:
    1: '331 &9Ruby_Marriage_Gem'
    2: '388 &9Emerald_Marriage_Gem'
    3: '264 &5Diamond_Marriage_Gem'
#The required distance (in blocks) between the priest and both couples:
priest-marriage-distance: 10
#The required distance (in blocks) between each partner:
marriage-couple-distance: 5
#
#The required distance for married couples to get bonus xp from each other
marriage-xp-bonus-distance: 30
#The percent of the killer's xp to give to their significant other (0.0 - 1.0)
marriage-xp-bonus-percent: 0.5
divorce-propose-cooldown: 5d
#Kissing cool-down (in seconds):
kiss-cooldown: 2
piggyback-cooldown: 10s
marriage-food-share-distance: 5
marriage-inventory-share-distance: 5
kiss-heal-amount: 1
login-petname-message: "{pet-name} has signed in"
logout-petname-message: "{pet-name} has signed out"
petname-change-spouse-message: "Your {spouse-petname} has given you the name {new-petname}"
default-world: world
#
sql:
 host: localhost
 dbname: socialcore
 user: changme
 pass: changeme

courts:
   category-config:
     abandoned-chest:
        permit-item: "paper 1 Unbreaking:1 name:&Chest_Permit lore:&6Awarded_to:_{citzen-name}|&5by_Judge:_{judge-name}|&2Permission_to_loot_chest|&2at_{location}|&7Permit|&3Bind On Pickup"
     abandoned:
        permit-item: "paper 1 Unbreaking:1 name:&9Building_Permit lore:&6Awarded_to:_{citzen-name}|&5by_Judge:_{judge-name}|&2Permission_to_build/destroy|&2at_{location}|&7Permit|&3Bind On Pickup"
     samesex-marriage:
        permissions:
          - "courts.samesex"
   notifier:
     events:
      on-login:
        - "judge-upcoming-case"
        - "participant-upcoming-case"
        - "ongoing-case-participant"
     messages:
       judge-upcoming-case:
         base-message: "Judge {name}, you have {case-name} at {case-datetime}"
         upcoming-time: 7d
       participant-upcoming-case:
         base-message: "You are involved in {case-name} at {case-datetime}"
         upcoming-time: 7d
       judge-inactive-judge:
         base-message: "You weer inactive for too many days and have been removed from office"
         timeout: 3d
       judge-inactive-all:
         base-message: "Judge {judge-name} was inactive for too many days and was removed from office"
       ongoing-case-all:
         enabled: true
         base-message: "{case-name} is currently in court"
       ongoing-case-participant:
         base-message: "You are involved in an ongoing court session, please teleport with /court tp"
       judge-removed-rating-judge:
         base-message: "You have been removed from office with an approval rating of {approval-rating}"
         timeout: 3d
       judge-removed-rating-all:
         base-message: "Judge {judge-name} has been removed from office with an approval rating of {approval-rating}"
       judge-nominated-self:
          base-message: "{player-name}, you have been nominated to become a judge"
          timeout: 3d
       judge-nominated-all:
          base-message: "{player-name} has been nominated to become a judge"
       judge-elected-all:
          base-message: "{judge-name} has been elected as a judge"
       case-assigned-time:
          base-message: "{judge-name} has scheduled {case-name} to {case-datetime}"
       secretary-removed:
          base-message: "{judge-name} has removed you as one of their secretaries"
          timeout: 3d
       vote-notification:
          approval: "Somebody approved of you, your approval rate is now {approval-rating} with {approvals} approvals and {disapprovals} disapprovals"
          disapproval: "Somebody approved of you, your approval rate is now {approval-rating} with {approvals} approvals and {disapprovals} disapprovals"
       vote-summary:
          approval: "{new-approvals} have newly approved of you {approval-rating}"
          disapproval: "{new-disapprovals} have newly disapproved of you {approval-rating}"
          both: "{new-approvals} have newly approved of you and {new-disapprovals} have disapproved of you "
       court-session-end:
          base-message: "{case-name} is now adorned by {judge-name}"

   silence-court-effects:
        particles:
                HEART:
                  data: 0
        sounds:
          ANVIL_USE:
            volume: 1
            pitch: 1
   court-rooms:
      test-courtroom:
        region: "test-courtroom"
        tp-location: world,0,64,0
        effects-location: world,0,64,0
        judge-chair-location: world,0,64,0
   max-judges: 5
   secretaries-per-judge: 5
   judge-inactive-days-allowed: 15
   judge-approval-rate-required: 60
   judge-approval-rate-demoted: 40
   judge-required-votes: 100
   max-judge-offline-time: 10m
   case-filing-cost: 100
   auto-save-interval: 1m
   nominate-cost: 1000
   fine-payment-percentage: 5
   fine-payment-interval: 5m
   citizen-stall-document-cooldown: 15s
   silence-mute-length: 10s
   max-fine: 10000
   judge-permissions:
      - "judge.test"
   secretary-permissions:
      - "sec.test"
   time-between-vote-messages: 30s
   court-session-teleport-effects:
         title:
           title: "&aJudge {judge-name} teleported to {location}"
           subtitle: "~~"
           fade-in: 1s
           stay: 40t
           fade-out: 10t
   court-session-start-effects:
      title:
        title: "&aJudge {judge-name} presiding over {case-name}"
        subtitle: "Quiet in the court"
        fade-in: 1s
        stay: 40t
        fade-out: 10t
   court-session-end-effects:
      title:
        title: "&aJudge {judge-name} has adorned {case-name}"
        subtitle: "~~"
        fade-in: 1s
        stay: 40t
        fade-out: 10t
   rewards:
      process:
        - gold_ingot 1 lore:&7lore
      court-vote:
        - gold_nugget 1 name:&aName
      judgment:
        - gold_block 1
      session:
        - redstone 1
   elections:
    wait-time: 7d
   lang:
      command-not-in-session: "This command can only be used while court is in session"
      election-no-slots: "There are no judge slots"
      judge-prefix: "<J>"
      court-session-plaintiff-prefix: "<Plaintiff>"
      court-session-defendant-prefix: "<Defendant>"
      case-category-descriptions:
          TRESPASSING: "Trespassing involves a player repeatedly entering a player's property even after being asked to leave."
          DIVORCE: "Divorce is when a married couple wishes to end their union."
          ABANDONED: "Cases concerning abandoned houses or towns"
          OTHER: "Cases which do not fit in any other category"

      confirm-nominate-self: "Typing /election nominateself again will nominate you in this election and charge you {cost} voxels"
      citizen-stall:
        case-already-filed: "Case has already been filed"
        case-book-empty: "This case book is empty"
        confirm: "Clicking this stall again will charge you {cost} voxels and give you court documents"
        gave-court-documents: "You have been given a book to make your case, right click the stall to submit it"
        on-cooldown: "Please wait before using this stall again"
        submitted: "Your case has been submitted for processing"
      secretary:
        requesting-message: "&aA request has been sent to {requested-name} to become your secretray."
        requested-confirm-message: "&aJudge {judge-name} has requested that you become their secretary. /secretary accept to accept or /secretary deny to deny this request."
        requested-accept-message: "&aYou have accepted {judge-name}'s request that you become their secretary"
        requested-deny-message: "You have denied {judge-name}'s request that you become their secretary"
        requester-accepted-message: "{requested-name} is now your secetary"
        requester-denied-message: "{requested-name} has denied your secetary request"

        removed-message: "You have removed {player-name} as your secretary"
        not-secretary-message: "{player-name} is not one of your secretaries"