name: SocialCore
main: com.nicholasdoherty.socialcore.SocialCore
version: 2.0
authors: [theMightyChain,pascoej,Gummybearking,GenSecrets]
depend: [Vault,Essentials]
loadafter: [Vault,TownyChat,Essentials]
softdepend: [ProtocolLib,WorldGuard,TownyChat]

api-version: 1.16

commands:
    wel:
        description: Welcome a player!
    welcome:
        description: Welcome a player!
    gender:
        description: Manage gender commands
    marriage:
        description: Marriage command
    court:
        usage: /court
        permission: sc.defaultperm
    judge:
        usage: /judge
        permission: sc.defaultperm
    policy:
        description: Policy command
    policies:
        description: Policies command