name: SocialCore
main: com.nicholasdoherty.socialcore.SocialCore
version: 1.3-Z54
authors: [theMightyChain,pascoej@murri.ca]
loadafter: [Werewolf,Vampires]
softdepend: [ProtocolLib,WorldGuard,TownyChat
]
commands:
    petname:
        usage: /petname [name]
        description: Give your significant other a pet name
        permission: sc.petname
    purgeinvalids:
        usage: /purgeinvalids
        description: Purges invalid marriages / engagements or fixes them.
        permission: sc.admin
    status:
        usage: /status <playername>
        description: Tells the martial status of a player
        permission: sc.status
    ttc:
        usage: /ttc
    court:
        usage: /court
    judges:
        usage: /judges
    judge:
        usage: /judge
    election:
        usage: /election
    share:
        usage: /<command>.
    secretary:
        usage: /secretary
    socialcore:
        description: Displays the current version of social core
        usage: /<command>.
        permission: sc.basic
    female:
        description: Set your gender to female
        usage: /<command>.
        permission: sc.gender
    male:
        description: Set your gender to male
        usage: /<command>.
        permission: sc.gender
    gender:
        description: Check your gender.
        usage: /<command>.
        permission: sc.gender
    marriage:
        description: View all marriage commands.
        usage: /<command>.
        permission: sc.marriage
    marriages:
        description: View all marriages
        permission: sc.view.marriages
    engagements:
        description: View all engagements
        permission: sc.view.engagements
    propose:
        description: Propose to a player
        permission: sc.propose
    unengage:
        description: Unengage your partner
        permission: sc.unengage
    marry:
        description: Marry two players
        permission: sc.priest
    divorce:
        description: File a divorce or complete a divorce
        permission: sc.fileDivorce
    divorces:
        description: View all pending divorces on the server
        permission: sc.view.divorces
    adivorce:
        description: Force a divorce
        permission: sc.admin
    amarry:
        description: Force a marriage
        permission: sc.admin
    aunengage:
        description: Force unengage
        permission: sc.admin
    emotes:
        description: Shows availible emotes
        permission: sc.emotes
    race:
        description: Race related commands
        permission: sc.race
    races:
        description: Race related commands
        permission: sc.race
    fixmarriages:
        description: fixes a bug
        permission: sc.admin
    getpermissions:
        description: View your permissions
        permission: sc.admin
permissions:
    sc.status:
        description: allows use of status command
        default: true
    sc.petname:
        description: allows you to use /petname
        default: true
    sc.racestatus:
        description: Lets you use /race status
        default: op
    sc.emotes:
        description: Required to show availible emotes
        default: true
    sc.gender:
        description: Required to check and set gender
        default: true
    sc.gender.others:
        description: Required to check other's gender
        default: true
    sc.set.others:
        description: Required set other's gender
        default: false
    sc.marriage:
        description: Required to view all marriage commands
        default: true
    sc.unengage:
        description: Required to unengage
        default: true
    sc.view.marriages:
        description: Required to view all marriages
        default: true
    sc.view.engagements:
        description: Required to view all engagements
        default: true
    sc.propose:
        description: Required to propose and accept/deny proposes
        default: true
    sc.priest:
        description: Required to marry a couple
        default: false
    sc.lawyer:
        description: Required to divorce a couple
        default: false
    sc.fileDivorce:
        description: Required to file divorce
        default: true
    sc.view.divorces:
        description: Required to view all pending divorces
        default: true
    sc.admin:
        description: Required to marry a couple
        default: false
    sc.samesex:
        description: Required to propose samesex
        default: false
    sc.race:
        description: Required to use races
        default: true
    sc.petname:
        description: Required to use petname
        default: true
    sc.race.issupernatural:
        description: Allows a player to be a different race than default
        default: false
    sc.viewspouseinventory:
        description: Allows player to view their spouse's inventory.
        default: true
    courts.admin:
        description: Allows use of courts admin commands
        default: op
    courts.mastercases:
        description: Allows viewing of /courts master cases
        default: op
    courts.run:
        description: Allows nominating of self to an election for judge
        default: false
    courts.nopay:
        description: Doesn't require payment for testing
        default: false